[package]
name = "shade"
version = "0.1.0"
edition = "2024"

[features]
default = []
debug-log = []

[dependencies]
async-channel = "2.5.0"
enumset = "1.1.10"
macroquad.workspace = true
slotmap = "1.0.7"
thiserror = "2.0.17"
ttmap = "0.3.0"
