name: Dependency Submission

on:
  push:
    branches: [ 'main' ]
    paths:
      - '**.gradle.*'
      - 'app/**/*'
      - 'gradle/**/*'

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
