name: PR Checks

on:
  pull_request:

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: "aarch64-linux-android, armv7-linux-androideabi, i686-linux-android, x86_64-linux-android"
          cache-workspaces: "."
          rustflags: ""

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: NDK cache
        id: cache-ndk
        env:
          cache-name: ndk-r25b-cache
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/android/sdk/ndk/27.1.12297006
          key: build-${{ env.cache-name }}

      - name: Download NDK
        run: |
          cd $ANDROID_HOME/cmdline-tools/latest/bin
          ./sdkmanager "ndk;27.1.12297006"

      - name: Build APK's
        run: ./gradlew assemble

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Luminara-APKs
          path: ./app/build/outputs/apk

  web-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: "wasm32-unknown-unknown"
          cache-workspaces: "."
          rustflags: ""

      - name: Build WASM
        run: ./wasm-build.py --profile web-release

      - name: Upload WASM Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
        with:
          manifest-path: ./Cargo.toml
